// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5nG0lY-RRTi7Slvtu1pQPV7n2HI2C6mY',
    appId: '1:245269299085:web:72a1f50062222b74a1c7c4',
    messagingSenderId: '245269299085',
    projectId: 'myfirstproject-cf199',
    authDomain: 'myfirstproject-cf199.firebaseapp.com',
    storageBucket: 'myfirstproject-cf199.appspot.com',
    measurementId: 'G-2BQ87Q5CNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhlM1KYjKcYkxH6Bv4-BtFWeUf9960Hy0',
    appId: '1:245269299085:android:2bf1eeaa48079f5ca1c7c4',
    messagingSenderId: '245269299085',
    projectId: 'myfirstproject-cf199',
    storageBucket: 'myfirstproject-cf199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABobQhbu8S86z6j8mNEvOjnedNCtTNh1s',
    appId: '1:245269299085:ios:f2287d7c4fa31a15a1c7c4',
    messagingSenderId: '245269299085',
    projectId: 'myfirstproject-cf199',
    storageBucket: 'myfirstproject-cf199.appspot.com',
    iosClientId: '245269299085-7qc0e7gl4p8f4p7s8q58ihu34vt0pjhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABobQhbu8S86z6j8mNEvOjnedNCtTNh1s',
    appId: '1:245269299085:ios:f2287d7c4fa31a15a1c7c4',
    messagingSenderId: '245269299085',
    projectId: 'myfirstproject-cf199',
    storageBucket: 'myfirstproject-cf199.appspot.com',
    iosClientId: '245269299085-7qc0e7gl4p8f4p7s8q58ihu34vt0pjhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );
}
